server:
 port: 8761
spring:
 application:
  name: eurekaserver
eureka:
 client:
  service-url: # eureka???????????eureka????????ip??
   defaultZone: http://127.0.0.1:8761/eureka
 server:
  eviction-interval-timer-in-ms: 10000 # ???????????????? -- 1
  renewal-percent-threshold: 0.85      # ????????85%????????????eureka??????????
 instance:
  lease-renewal-interval-in-seconds: 5 # ????????????? 1 ??
